language: julia
os:
  - linux
julia:
  - nightly
  - 1.6
​
jobs:
  allow_failures:
    - julia: nightly
​
notifications:
  email: false

  after_success:
- julia -e 'using Pkg; cd(Pkg.dir("RatingCurves")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
